
let zh=false;let current=null;let mockQs=[],mockIndex=0,mockAnswers=[];
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function save(k,v){localStorage.setItem('ndhce_med_'+k,JSON.stringify(v))}function load(k,d){try{return JSON.parse(localStorage.getItem('ndhce_med_'+k))??d}catch{return d}}
function renderLearn(){const box=$('#learnGrid');box.innerHTML='';LEARN.forEach((s,i)=>{const d=document.createElement('details');d.className='learn-section';d.innerHTML=`<summary>${s[0]} · ${s[1]}</summary><div class="learn-items">${s[2].map(x=>`<article class="learn-item"><h4>${x[0]}</h4><p>${x[1]}</p><p class="zh">${x[2]}</p></article>`).join('')}</div>`;d.addEventListener('toggle',()=>{if(d.open){let seen=new Set(load('learn',[]));seen.add(i);save('learn',[...seen]);updateStats()}});box.appendChild(d)})}
function categories(){return ['All',...new Set(QUESTIONS.map(q=>q.category))]}
function renderCats(){category.innerHTML=categories().map(c=>`<option>${c}</option>`).join('')}
function pickQuestion(){let pool=category.value==='All'?QUESTIONS:QUESTIONS.filter(q=>q.category===category.value);current=pool[Math.floor(Math.random()*pool.length)];renderQuestion(current,'practiceCard',false)}
function renderQuestion(q,id,mock){let box=document.getElementById(id);box.innerHTML=`<div class="question-card"><div class="qmeta">${q.category}${mock?` · ${mockIndex+1}/${mockQs.length}`:''}</div><h3>${q.stem}</h3><p class="qzh">${q.stemZh}</p>${mock?`<div class="mock-progress"><div style="width:${(mockIndex+1)/mockQs.length*100}%"></div></div>`:''}<div class="options">${q.options.map((o,i)=>`<button class="option" data-i="${i}"><b>${String.fromCharCode(65+i)}.</b> ${o.en}<br><span class="zh">${o.zh}</span></button>`).join('')}</div><div class="feedback"></div>${mock?`<div class="mock-nav"><button id="prevMock" ${mockIndex===0?'disabled':''}>Previous</button><button id="nextMock">${mockIndex===mockQs.length-1?'Finish':'Next'}</button></div>`:''}</div>`;
box.querySelectorAll('.option').forEach(b=>b.onclick=()=>selectAnswer(q,box,+b.dataset.i,mock));if(mock&&mockAnswers[mockIndex]!=null){selectAnswer(q,box,mockAnswers[mockIndex],true,true)}if(mock){$('#prevMock').onclick=()=>{mockIndex--;renderMockQ()};$('#nextMock').onclick=()=>{if(mockAnswers[mockIndex]==null){alert('Choose an answer first.');return}if(mockIndex===mockQs.length-1)finishMock();else{mockIndex++;renderMockQ()}}}}
function selectAnswer(q,box,choice,mock,silent=false){if(mockAnswers[mockIndex]!=null&&mock)return;box.querySelectorAll('.option').forEach((b,i)=>{b.disabled=true;if(i===q.correct)b.classList.add('correct');else if(i===choice)b.classList.add('wrong')});let f=box.querySelector('.feedback');f.innerHTML=`<div class="rationales">${q.rationales.map((r,i)=>`<div class="rationale ${i===q.correct?'good':'bad'}"><p><b>${String.fromCharCode(65+i)}.</b> ${r.en}</p><p class="zh">${r.zh}</p></div>`).join('')}</div>`;if(mock){mockAnswers[mockIndex]=choice;save('mockAnswers',mockAnswers)}else if(!silent){let p=load('practice',{correct:0,total:0});p.total++;if(choice===q.correct)p.correct++;save('practice',p);updateStats()}}
function startMock(){mockQs=[...QUESTIONS].sort(()=>Math.random()-.5).slice(0,20);mockAnswers=Array(mockQs.length).fill(null);mockIndex=0;save('mockQs',mockQs);save('mockAnswers',mockAnswers);renderMockQ()}
function renderMockQ(){renderQuestion(mockQs[mockIndex],'mockArea',true)}
function finishMock(){let correct=mockQs.reduce((n,q,i)=>n+(mockAnswers[i]===q.correct),0);let pct=Math.round(correct/mockQs.length*100);save('mockResult',{correct,total:mockQs.length,pct,date:new Date().toISOString()});mockArea.innerHTML=`<div class="mock-results"><div class="score">${pct}%</div><h3>${correct} / ${mockQs.length} correct</h3><p>${pct>=80?'Strong emergency-response readiness.':'Review the missed emergency patterns, especially first actions and contraindications.'}</p><p class="zh">${pct>=80?'急症应对准备充分。':'请复习错题，尤其关注首要行动与禁忌操作。'}</p><div class="mock-actions"><button class="primaryBtn" onclick="startMock()">Retake</button><button onclick="showView('learn')">Review Learn</button></div></div>`;updateStats()}
function showView(id){$$('.view').forEach(v=>v.classList.add('hidden'));$('#'+id).classList.remove('hidden');scrollTo({top:document.querySelector('main').offsetTop,behavior:'smooth'});if(id==='practice'&&!current)pickQuestion();if(id==='mock'&&!mockQs.length)mockArea.innerHTML=`<div class="mock-intro"><h3>20-question Medical Emergencies Mock Exam</h3><p>Immediate feedback appears after each answer. A final score is saved on this device.</p><p class="zh">20 题医疗急症模拟考试。每题作答后显示完整双语解析，成绩保存在本设备。</p><button class="primaryBtn" onclick="startMock()">Start exam · 开始考试</button></div>`}
function updateStats(){let seen=load('learn',[]);learnStat.textContent=Math.round(seen.length/LEARN.length*100)+'%';let p=load('practice',{correct:0,total:0});practiceStat.textContent=p.correct+'/'+p.total;let m=load('mockResult',null);mockStat.textContent=m?m.pct+'%':'Not started'}
function toggleLang(){zh=!zh;$$('[data-en]').forEach(e=>e.textContent=zh?e.dataset.zh:e.dataset.en);document.documentElement.lang=zh?'zh':'en'}
renderLearn();renderCats();updateStats();$$('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));$$('.homeBtn').forEach(b=>b.onclick=()=>scrollTo({top:0,behavior:'smooth'}));langBtn.onclick=toggleLang;newQuestion.onclick=pickQuestion;category.onchange=pickQuestion;
